# Assignment 5 - NumPy Introduction

## Q1. Basic Operations on NumPy Array

In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


## Q2(a). Reverse the NumPy Array

In [23]:
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


## Q2(b). Most Frequent Value and Its Indices

In [24]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = counts.max()

    most_frequent_values = values[counts == max_count]

    for value in most_frequent_values:
        indices = np.where(arr == value)[0]
        print("Value:", value)
        print("Frequency:", max_count)
        print("Indices:", indices)
        print()

print("For x:")
most_frequent(x)

print("For y:")
most_frequent(y)

For x:
Value: 1
Frequency: 5
Indices: [0 5 7 8 9]

For y:
Value: 1
Frequency: 3
Indices: [0 1 2]

Value: 3
Frequency: 3
Indices: [4 8 9]



## Q3. Accessing Elements of a 2-D Array

In [25]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


## Q4. NumPy Array Using linspace()

In [26]:
ucs420_Arnav = np.linspace(10, 100, 25)

print("Array:")
print(ucs420_Arnav)

print("Dimensions:", ucs420_Arnav.ndim)
print("Shape:", ucs420_Arnav.shape)
print("Total elements:", ucs420_Arnav.size)
print("Data type:", ucs420_Arnav.dtype)
print("Total bytes:", ucs420_Arnav.nbytes)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200


In [27]:
reshaped_Arnav = ucs420_Arnav.reshape(25, 1)

print("Reshaped array:")
print(reshaped_Arnav)

print("Transpose:")
print(reshaped_Arnav.T)

Reshaped array:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


### Observation

For a 1-D array, the T attribute does not change the array into a row or column. 
After reshaping the array to 25 x 1, the T attribute can be used to get its transpose.

## Q5. Operations on a 2-D NumPy Array

In [28]:
ucs420_Arnav = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_Arnav)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [29]:
print("Mean:", np.mean(ucs420_Arnav))
print("Median:", np.median(ucs420_Arnav))
print("Maximum:", np.max(ucs420_Arnav))
print("Minimum:", np.min(ucs420_Arnav))
print("Unique elements:", np.unique(ucs420_Arnav))

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [30]:
reshaped_ucs420_Arnav = ucs420_Arnav.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_Arnav)

Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [31]:
resized_ucs420_Arnav = np.resize(ucs420_Arnav, (2, 3))

print("Resized array:")
print(resized_ucs420_Arnav)

Resized array:
[[10 20 30]
 [40 50 60]]
