# Assignment 6 - NumPy-II

## Q1. Sensor Readings and Vectorization

In [28]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2

print("Original temperature:", temperature)
print("Corrected temperature:", corrected_temperature)

Original temperature: [25 28 31 35 38 27 33 40]
Corrected temperature: [27 30 33 37 40 29 35 42]


In [29]:
fahrenheit = (9 / 5) * corrected_temperature + 32

print("Temperature in Fahrenheit:", fahrenheit)

Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [30]:
above_32 = corrected_temperature[corrected_temperature > 32]

print("Readings greater than 32°C:", above_32)
print("Number of readings greater than 32°C:", len(above_32))

Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


### Explanation

Vectorization allows NumPy to perform operations on the whole array at once instead of using a loop for every value. Boolean indexing allows us to directly select the values that satisfy a condition. These operations are shorter and generally faster than explicitly iterating through every element.

## Q2. Daily Steps Analysis

In [31]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps array:")
print(steps)

Steps array:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


In [32]:
print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500


In [33]:
day_totals = np.sum(steps, axis=0)

print("Total steps for each day:", day_totals)

Total steps for each day: [26500 27300 30400]


In [34]:
user_totals = np.sum(steps, axis=1)

print("Total steps for each user:", user_totals)

Total steps for each user: [18300 24500 14400 27000]


In [35]:
max_index = np.argmax(steps)
max_position = np.unravel_index(max_index, steps.shape)

print("Position of maximum value:", max_position)
print("Maximum value:", steps[max_position])

Position of maximum value: (np.int64(3), np.int64(2))
Maximum value: 9500


## Q3. NumPy Slicing, Views, Copies and Reshaping

In [36]:
original = np.array([1, 2, 3, 4, 5, 6])

print("Original:", original)

Original: [1 2 3 4 5 6]


In [37]:
subset = original[1:5]

subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [38]:
copied_array = original[1:5].copy()

copied_array[0] = 500

print("Original after modifying copied array:", original)
print("Copied array:", copied_array)

Original after modifying copied array: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


In [39]:
matrix = np.arange(1, 13).reshape(3, 4)

print("3 x 4 matrix:")
print(matrix)

3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]


In [41]:
flattened = matrix.flatten()
raveled = matrix.ravel()

print("Using flatten():", flattened)
print("Using ravel():", raveled)

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
raveled = matrix.ravel()

raveled[0] = 100

print("Raveled array:", raveled)
print("Original matrix after modifying ravel():")
print(matrix)

Raveled array: [100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix after modifying ravel():
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
matrix = np.arange(1, 13).reshape(3, 4)

flattened = matrix.flatten()

flattened[0] = 200

print("Flattened array:", flattened)
print("Original matrix after modifying flatten():")
print(matrix)

Flattened array: [200   2   3   4   5   6   7   8   9  10  11  12]
Original matrix after modifying flatten():
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


## Q4. Cognitive Assistive System Using OLS

In [45]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("X:")
print(X)

print("y:")
print(y)

X:
[[ 6 70  3]
 [ 5 50  6]
 [ 8 80  2]
 [ 4 30  8]]
y:
[40 65 30 85]


In [46]:
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

Shape of X: (4, 3)
Dimensions of X: 2


In [47]:
X_T = X.T

print("X transpose:")
print(X_T)

X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


### Meaning of Transpose

The original X matrix has one row for each user and one column for each feature. After transpose, each row represents one feature and the columns represent the users.

In [48]:
XTX = X.T @ X

print("X.T @ X:")
print(XTX)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [49]:
XTX_inv = np.linalg.inv(XTX)

print("Inverse of X.T @ X:")
print(XTX_inv)

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [50]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("OLS coefficients:")
print(beta)

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]


### Interpretation of Coefficients

The three coefficients correspond to sleep hours, activity level, and stress level respectively.

A coefficient represents the estimated change in the assistance score for a one-unit change in that feature while keeping the other features constant.

The sign of a coefficient shows whether the feature has a positive or negative relationship with the predicted assistance score.

In [51]:
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Predicted assistance score: 75.27862544779117
